@echo off
echo Starting Backend...
start cmd /k "cd c:\Users\Nehemiah\Desktop\Django Senior Project\Backend && .venv\Scripts\activate.bat && python manage.py runserver"
echo Starting Frontend...
start cmd /k "cd c:\Users\Nehemiah\Desktop\Django Senior Project\Frontend && npm run dev"
echo Both servers starting...
