# Generated by Django 6.0.2 on 2026-02-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('location_lost', models.CharField(max_length=255)),
                ('date_lost', models.DateTimeField(auto_now_add=True)),
                ('is_found', models.BooleanField(default=False)),
            ],
        ),
    ]
