# Generated by Django 6.0.2 on 2026-04-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_lostpet_created_at_lostpet_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpet',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of where pet was lost', null=True),
        ),
        migrations.AddField(
            model_name='lostpet',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of where pet was lost', null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of sighting location', null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of sighting location', null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
