# Generated by Django 6.0.2 on 2026-04-07 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_lostpet_latitude_lostpet_longitude_sighting_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='confidence',
        ),
        migrations.AlterField(
            model_name='sighting',
            name='lost_pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='pets.lostpet'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to=settings.AUTH_USER_MODEL),
        ),
    ]
