# Generated by Django 6.0.2 on 2026-04-14 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_remove_sighting_confidence_alter_sighting_lost_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='sighting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='pets.sighting'),
        ),
    ]
