# Generated by Django 5.2.13 on 2026-04-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_match_sighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
